
import { Item, NPC } from './types';

export const INITIAL_ITEMS: Item[] = [
  // D&D 5e
  { id: '1', name: 'Longsword', price: 15, currency: 'gp', weight: '3lb', rarity: 'Common', type: 'Weapon', system: 'D&D 5e' },
  { id: '2', name: 'Potion of Healing', price: 50, currency: 'gp', weight: '0.5lb', rarity: 'Common', type: 'Potion', system: 'D&D 5e' },
  { id: '3', name: 'Bag of Holding', price: 500, currency: 'gp', weight: '15lb', rarity: 'Uncommon', type: 'MagicItem', system: 'D&D 5e' },
  { id: '4', name: 'Plate Armor', price: 1500, currency: 'gp', weight: '65lb', rarity: 'Rare', type: 'Armor', system: 'D&D 5e' },
  
  // Tormenta 20
  { id: '5', name: 'Espada Bastarda', price: 35, currency: 'T$', weight: '2kg', rarity: 'Common', type: 'Weapon', system: 'Tormenta 20' },
  { id: '6', name: 'Poção de Curar Ferimentos', price: 30, currency: 'T$', weight: '0.5kg', rarity: 'Common', type: 'Potion', system: 'Tormenta 20' },
  { id: '7', name: 'Mosquete', price: 500, currency: 'T$', weight: '5kg', rarity: 'Uncommon', type: 'Weapon', system: 'Tormenta 20' },
  
  // Generic/Daggerheart
  { id: '8', name: 'Rope (50ft)', price: 1, currency: 'gp', weight: '10lb', rarity: 'Common', type: 'Gear', system: 'Generic' },
  { id: '9', name: 'Torch', price: 1, currency: 'cp', weight: '1lb', rarity: 'Common', type: 'Gear', system: 'Generic' },
  { id: '10', name: 'Vorpal Blade', price: 50000, currency: 'gp', weight: '3lb', rarity: 'Legendary', type: 'Weapon', system: 'Generic' },
];

export const INITIAL_SHOP_TYPES = ['Blacksmith', 'Alchemist', 'General', 'Magic', 'Tavern'];
export const INITIAL_ITEM_TYPES = ['Weapon', 'Armor', 'Potion', 'Gear', 'MagicItem', 'Service'];
export const INITIAL_SYSTEMS = ['D&D 5e', 'Tormenta 20', 'Generic', 'Pathfinder 2e', 'Daggerheart'];
export const INITIAL_RARITIES = ['Common', 'Uncommon', 'Rare', 'Epic', 'Legendary', 'Artifact'];

export const INITIAL_NPCS: NPC[] = [
  { id: 'npc_1', name: 'Grom Ironbeard', race: 'Dwarf', personality: 'Grumpy but fair', description: 'A master smith with a singed beard.', avatarUrl: 'https://picsum.photos/seed/dwarf1/200' },
  { id: 'npc_2', name: 'Elara Moonwhisper', race: 'Elf', personality: 'Mysterious and quiet', description: 'Expert in ancient artifacts.', avatarUrl: 'https://picsum.photos/seed/elf1/200' },
  { id: 'npc_3', name: 'Barnaby Stout', race: 'Halfling', personality: 'Cheerful and chatty', description: 'Runs the best tavern in town.', avatarUrl: 'https://picsum.photos/seed/halfling1/200' },
  { id: 'npc_4', name: 'Kriv', race: 'Dragonborn', personality: 'Proud and honorable', description: 'Sells weapons of war.', avatarUrl: 'https://picsum.photos/seed/dragon1/200' },
  { id: 'npc_5', name: 'Zaroth the Mad', race: 'Tiefling', personality: 'Unpredictable', description: 'Alchemist who tests his own potions.', avatarUrl: 'https://picsum.photos/seed/tiefling1/200' },
];

export const NPC_NAMES = ['Tharivol', 'Grom', 'Elara', 'Vex', 'Bram', 'Seraphina', 'Durnan', 'Mika', 'Zaroth', 'Lira'];
export const NPC_RACES = ['Human', 'Elf', 'Dwarf', 'Orc', 'Tiefling', 'Gnome', 'Halfling', 'Dragonborn'];
export const NPC_TRAITS = ['Grumpy', 'Cheerful', 'Mysterious', 'Greedy', 'Helpful', 'Nervous', 'Arrogant', 'Wise'];

export const FLAVOR_TEXTS = [
  "The air smells of sulfur and ozone.",
  "Dust motes dance in the shafts of light piercing the gloom.",
  "You hear the rhythmic hammering of metal in the distance.",
  "Shelves are packed to the brim with curiosities.",
  "A sleeping cat lies on the counter, indifferent to your presence.",
  "The shopkeeper eyes you suspiciously from the shadows.",
  "Sweet incense burns, making you feel slightly drowsy."
];

export const TRANSLATIONS = {
  en: {
    shopGenerator: "Shop Generator",
    generate: "Generate Shop",
    save: "Save Shop",
    settings: "Settings",
    inventory: "Item Manager",
    worldManager: "World Manager",
    npcManager: "NPC Manager",
    rulesManager: "Rules & Types",
    exportPng: "Export PNG",
    exportJson: "Export JSON",
    shopName: "Shop Name",
    owner: "Owner",
    priceModifier: "Price Modifier",
    allowBarter: "Allows Barter",
    items: "Items",
    type: "Type",
    system: "System",
    actions: "Actions",
    savedShops: "Saved Shops",
    world: "World",
    import: "Import Items (JSON)",
    filters: "Filters",
    newItem: "New Item",
    newCity: "New City",
    newNPC: "New NPC",
    edit: "Edit",
    delete: "Delete",
    name: "Name",
    price: "Price",
    add: "Add",
    update: "Update",
    editShop: "Edit Shop Details",
    editNPC: "Edit NPC",
    editItems: "Edit Inventory Items",
    addItemToShop: "Add Item to Shop",
    shopLocation: "Location (City)",
    weight: "Weight",
    rarity: "Rarity",
    currency: "Currency",
    minItems: "Min Items",
    maxItems: "Max Items",
    selectNPC: "Select Shopkeeper",
    randomNPC: "Random NPC",
    randomCity: "Random City",
    race: "Race",
    personality: "Personality",
    description: "Description",
    avatarUrl: "Image URL",
    itemCount: "Item Count",
    remove: "Remove",
    search: "Search",
    noShops: "No saved shops.",
    processImport: "Process Import",
    primaryColor: "Primary Color",
    secondaryColor: "Secondary Color",
    unknownLocation: "Unknown Location",
    close: "Close",
    categoryEconomy: "Category Economy (Price %)",
    shopTypes: "Shop Types",
    itemTypes: "Item Types",
    systems: "Game Systems",
    rarities: "Rarities",
    addType: "Add Type",
    typePlaceholder: "e.g. Relic",
    all: "All",
    language: "Language",
    enterNewSystem: "Enter new System Name:",
    enterNewRarity: "Enter new Rarity Name:",
    enterCityName: "Enter city name...",
    exportData: "Export Data",
    importData: "Import File",
    importSuccess: "Data imported successfully!",
    importError: "Error importing data. Check JSON format.",
    shopColor: "Shop Theme Color",
    tutorial: "Tutorial",
    tutorialTitle: "How to use Shop Master",
    editItemFull: "Edit Item Details",
    saveChanges: "Save Changes",
    tutorialContent: {
        gen: "Generator: Configure filters (Type, System), select an NPC (or random), and generate unique shops.",
        inv: "Inventory: Manage the global pool of items. Add your own items here to appear in future generations.",
        world: "World: Manage cities and locations where shops can spawn.",
        npc: "NPCs: Create custom shopkeepers to give personality to your shops.",
        rules: "Rules: Customize the drop-down lists (Systems, Rarities, Types) to fit your RPG campaign."
    }
  },
  pt: {
    shopGenerator: "Gerador de Loja",
    generate: "Gerar Loja",
    save: "Salvar Loja",
    settings: "Configurações",
    inventory: "Gerenciar Itens",
    worldManager: "Gerenciar Mundo",
    npcManager: "Gerenciar NPCs",
    rulesManager: "Regras e Tipos",
    exportPng: "Exportar PNG",
    exportJson: "Exportar JSON",
    shopName: "Nome da Loja",
    owner: "Proprietário",
    priceModifier: "Modif. Preço",
    allowBarter: "Aceita Escambo",
    items: "Itens",
    type: "Tipo",
    system: "Sistema",
    actions: "Ações",
    savedShops: "Lojas Salvas",
    world: "Mundo",
    import: "Importar Itens (JSON)",
    filters: "Filtros",
    newItem: "Novo Item",
    newCity: "Nova Cidade",
    newNPC: "Novo NPC",
    edit: "Editar",
    delete: "Excluir",
    name: "Nome",
    price: "Preço",
    add: "Adicionar",
    update: "Atualizar",
    editShop: "Editar Detalhes",
    editNPC: "Editar NPC",
    editItems: "Editar Itens do Inventário",
    addItemToShop: "Adicionar Item à Loja",
    shopLocation: "Localização (Cidade)",
    weight: "Peso",
    rarity: "Raridade",
    currency: "Moeda",
    minItems: "Mín. Itens",
    maxItems: "Máx. Itens",
    selectNPC: "Selecione o Vendedor",
    randomNPC: "NPC Aleatório",
    randomCity: "Cidade Aleatória",
    race: "Raça",
    personality: "Personalidade",
    description: "Descrição",
    avatarUrl: "URL da Imagem",
    itemCount: "Qtd. Itens",
    remove: "Remover",
    search: "Buscar",
    noShops: "Nenhuma loja salva.",
    processImport: "Processar Importação",
    primaryColor: "Cor Primária",
    secondaryColor: "Cor Secundária",
    unknownLocation: "Local Desconhecido",
    close: "Fechar",
    categoryEconomy: "Economia por Categoria (% do Preço)",
    shopTypes: "Tipos de Loja",
    itemTypes: "Tipos de Item",
    systems: "Sistemas de RPG",
    rarities: "Raridades",
    addType: "Adicionar Tipo",
    typePlaceholder: "ex: Relíquia",
    all: "Todos",
    language: "Idioma",
    enterNewSystem: "Nome do Novo Sistema:",
    enterNewRarity: "Nome da Nova Raridade:",
    enterCityName: "Nome da cidade...",
    exportData: "Exportar Dados",
    importData: "Importar Arquivo",
    importSuccess: "Dados importados com sucesso!",
    importError: "Erro ao importar. Verifique o JSON.",
    shopColor: "Cor da Loja",
    tutorial: "Tutorial",
    tutorialTitle: "Como usar o Shop Master",
    editItemFull: "Editar Detalhes do Item",
    saveChanges: "Salvar Alterações",
    tutorialContent: {
        gen: "Gerador: Configure os filtros (Tipo de Loja, Sistema), escolha um NPC (ou deixe aleatório) e gere lojas únicas.",
        inv: "Inventário: Gerencie o banco de dados global de itens. Itens criados aqui aparecerão em gerações futuras.",
        world: "Mundo: Gerencie as cidades e locais onde as lojas podem aparecer.",
        npc: "NPCs: Crie vendedores personalizados para dar personalidade às suas lojas.",
        rules: "Regras: Personalize as listas de opções (Sistemas, Raridades, Tipos) para se adequar à sua campanha de RPG."
    }
  },
  es: {
    shopGenerator: "Generador de Tiendas",
    generate: "Generar Tienda",
    save: "Guardar Tienda",
    settings: "Ajustes",
    inventory: "Gestor de Artículos",
    worldManager: "Gestor de Mundo",
    npcManager: "Gestor de NPCs",
    rulesManager: "Reglas y Tipos",
    exportPng: "Exportar PNG",
    exportJson: "Exportar JSON",
    shopName: "Nombre de la Tienda",
    owner: "Propietario",
    priceModifier: "Modif. Precio",
    allowBarter: "Permite Trueque",
    items: "Artículos",
    type: "Tipo",
    system: "Sistema",
    actions: "Acciones",
    savedShops: "Tiendas Guardadas",
    world: "Mundo",
    import: "Importar (JSON)",
    filters: "Filtros",
    newItem: "Nuevo Artículo",
    newCity: "Nueva Ciudad",
    newNPC: "Nuevo NPC",
    edit: "Editar",
    delete: "Borrar",
    name: "Nombre",
    price: "Precio",
    add: "Añadir",
    update: "Actualizar",
    editShop: "Editar Detalles",
    editNPC: "Editar NPC",
    editItems: "Editar Artículos del Inventario",
    addItemToShop: "Añadir Artículo a Tienda",
    shopLocation: "Ubicación (Ciudad)",
    weight: "Peso",
    rarity: "Rareza",
    currency: "Moneda",
    minItems: "Mín. Items",
    maxItems: "Max. Items",
    selectNPC: "Seleccionar Vendedor",
    randomNPC: "NPC Aleatorio",
    randomCity: "Ciudad Aleatoria",
    race: "Raza",
    personality: "Personalidad",
    description: "Descripción",
    avatarUrl: "URL de Imagen",
    itemCount: "Cant. Items",
    remove: "Remover",
    search: "Buscar",
    noShops: "Sin tiendas guardadas.",
    processImport: "Procesar Importación",
    primaryColor: "Color Primario",
    secondaryColor: "Color Secundario",
    unknownLocation: "Ubicación Desconocida",
    close: "Cerrar",
    categoryEconomy: "Economía por Categoría (% Precio)",
    shopTypes: "Tipos de Tienda",
    itemTypes: "Tipos de Artículo",
    systems: "Sistemas de Juego",
    rarities: "Rarezas",
    addType: "Añadir Tipo",
    typePlaceholder: "ej: Reliquia",
    all: "Todos",
    language: "Idioma",
    enterNewSystem: "Nombre del Nuevo Sistema:",
    enterNewRarity: "Nombre de la Nueva Rareza:",
    enterCityName: "Nombre de la ciudad...",
    exportData: "Exportar Datos",
    importData: "Importar Archivo",
    importSuccess: "¡Datos importados con éxito!",
    importError: "Error al importar. Verifique JSON.",
    shopColor: "Color de Tienda",
    tutorial: "Tutorial",
    tutorialTitle: "Cómo usar Shop Master",
    editItemFull: "Editar Detalles del Artículo",
    saveChanges: "Guardar Cambios",
    tutorialContent: {
        gen: "Generador: Configure filtros (Tipo, Sistema), seleccione un NPC (o aleatorio) y genere tiendas únicas.",
        inv: "Inventario: Gestione el conjunto global de artículos. Añada sus propios artículos aquí para futuras generaciones.",
        world: "Mundo: Gestione ciudades y lugares donde pueden aparecer las tiendas.",
        npc: "NPCs: Cree vendedores personalizados para dar personalidad a sus tiendas.",
        rules: "Reglas: Personalice las listas desplegables (Sistemas, Rarezas, Tipos) para su campaña."
    }
  }
};
